### ISSUE TITLE
No responsive design

### ISSUE THREAD

**Issue by Muhidin90** [IBUNHABIBU/final-capstone#2]
hey there, I want to inform you that your web application is not responsive in the manner that it is not user-friendly in mobile devices, kindly work on that so that it could support multiple devices screen for a better user experience.

**Comment by IBUNHABIBU** [comment]
I have resolved the issue of the website to be responsive

**Comment by IBUNHABIBU** [comment]
Now is responsive

**Comment by IBUNHABIBU** [comment]
- [x] Responsive typograph
- [ ] Responsive layout
- [ ] responsive images

**Comment by IBUNHABIBU** [comment]
@Muhidin90  we are halfway to making it responsive

**Comment by IBUNHABIBU** [comment]
Now the page if fully responsive [link](...)
